# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Crypto-trade CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
          os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: |
            npm install
            npm run lint
            npm run test
            npm run build

  semantic-release:
    run-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: npm set-script prepare ""
      - run: npm install
      - run: npm run build
      - run: cp "package.json" "./build/package.json"
      - run: zip -r build.zip build
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cp "./build/package.json" "package.json"
      - run: npm set-script prepare "husky install"
      - run: |
          cp "./build/package.json" "package.json"
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"
          git add package.json
          git commit -m "chore(release): package.json update [skip ci]"
          git push origin main
